/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTsxMockRouteImport } from './routes/auth.tsx.mock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTsxMockRoute = AuthTsxMockRouteImport.update({
  id: '/auth/tsx/mock',
  path: '/auth/tsx/mock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/tsx/mock': typeof AuthTsxMockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/tsx/mock': typeof AuthTsxMockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/tsx/mock': typeof AuthTsxMockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/tsx/mock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/tsx/mock'
  id: '__root__' | '/' | '/auth/tsx/mock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthTsxMockRoute: typeof AuthTsxMockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/tsx/mock': {
      id: '/auth/tsx/mock'
      path: '/auth/tsx/mock'
      fullPath: '/auth/tsx/mock'
      preLoaderRoute: typeof AuthTsxMockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthTsxMockRoute: AuthTsxMockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
